name: ci

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: osmarpetry/.github/.github/workflows/node.yml@main

  dependabot:
    needs: [build]
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    uses: osmarpetry/.github/.github/workflows/dependabot-automerge.yml@main
